name: TF_2_4_py_3_8
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - argh=0.26.2
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - autopep8=1.5.4
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cloudpickle=1.6.0
  - cryptography=3.1.1
  - cudatoolkit=11.0.221
  - cudnn=8.0.5.39
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.10
  - flake8=3.8.4
  - fontconfig=2.13.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - glib=2.56.2
  - graphite2=1.3.14
  - graphviz=2.40.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.1
  - jeepney=0.4.3
  - joblib=0.17.0
  - jpeg=9b
  - jupyterlab_pygments=0.1.2
  - keyring=21.4.0
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - nbclient=0.5.1
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - numpy-base=1.19.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - pathtools=0.1.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.3.3
  - pixman=0.40.0
  - pluggy=0.13.1
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python_abi=3.8
  - pytz=2020.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - rope=0.18.0
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - secretstorage=3.1.2
  - setuptools=52.0.0
  - sip=4.19.24
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.33.0
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - ujson=4.0.1
  - urllib3=1.25.11
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - wurlitzer=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
      - absl-py==0.11.0
      - anyio==3.7.1
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.12.1
      - beautifulsoup4==4.12.2
      - cachetools==4.2.1
      - charset-normalizer==3.2.0
      - clearml==0.17.4
      - click==7.1.2
      - cmake==3.27.2
      - colorama==0.4.4
      - configparser==5.0.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.2
      - fastjsonschema==2.18.0
      - filelock==3.12.2
      - flatbuffers==1.12
      - fqdn==1.5.1
      - funcsigs==1.0.2
      - furl==2.1.0
      - gast==0.3.3
      - gitdb==4.0.5
      - gitpython==3.1.12
      - google-auth==1.24.0
      - google-auth-oauthlib==0.4.2
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - humanfriendly==9.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - isoduration==20.11.0
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.4
      - jupyterlab-server==2.24.0
      - keras-preprocessing==1.1.2
      - keras-tuner==1.0.3
      - kt-legacy==1.0.5
      - lit==16.0.6
      - markdown==3.3.3
      - markupsafe==2.1.3
      - mistune==3.0.1
      - mpmath==1.3.0
      - nbconvert==7.7.3
      - nbformat==5.9.2
      - networkx==3.1
      - notebook-shim==0.2.3
      - numpy==1.19.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.1.0
      - opt-einsum==3.3.0
      - orderedmultidict==1.0.1
      - overlap==0.1.1
      - overrides==7.4.0
      - packaging==23.1
      - pathlib2==2.3.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.10.0
      - pooch==1.7.0
      - prometheus-client==0.17.1
      - promise==2.3
      - protobuf==3.14.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydot==1.4.2
      - pyjwt==2.0.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pyvista==0.41.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - requests-file==1.5.1
      - requests-oauthlib==1.3.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.9.2
      - rsa==4.7
      - scooby==0.7.2
      - send2trash==1.8.2
      - sentry-sdk==0.19.5
      - shortuuid==1.0.1
      - smmap==3.0.5
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - subprocess32==3.5.4
      - sympy==1.12
      - tabulate==0.8.8
      - tensorboard==2.4.1
      - tensorboard-plugin-wit==1.8.0
      - tensorflow==2.4.1
      - tensorflow-addons==0.12.1
      - tensorflow-estimator==2.4.0
      - termcolor==1.1.0
      - terminado==0.17.1
      - terminaltables==3.1.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.0.1
      - tornado==6.3.2
      - tqdm==4.57.0
      - trains==0.16.4
      - traitlets==5.9.0
      - triton==2.0.0
      - typeguard==2.11.1
      - typing-extensions==4.7.1
      - uri-template==1.3.0
      - vtk==9.2.6
      - wandb==0.10.22
      - webcolors==1.13
      - websocket-client==1.6.1
      - werkzeug==1.0.1
      - wrapt==1.12.1
