name: preprocessingVOF
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.10.14
  - cached-property=1.5.1
  - certifi=2020.6.20
  - cffi=1.14.3
  - cftime=1.2.1
  - chardet=3.0.4
  - cloudpickle=1.6.0
  - colorcet=2.0.2
  - cryptography=3.1.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.1.1
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.16
  - embree=2.17.7
  - entrypoints=0.3
  - expat=2.2.10
  - ffmpeg=4.3.1
  - flake8=3.8.4
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - geos=3.8.1
  - glib=2.56.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - imagesize=1.2.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.1
  - jeepney=0.4.3
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9d
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - keyring=21.4.0
  - kiwisolver=1.2.0
  - krb5=1.17.2
  - lame=3.100
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - meshio=4.3.8
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - netcdf4=1.5.3
  - nettle=3.6
  - networkx=2.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - param=1.9.3
  - parso=0.7.0
  - pathtools=0.1.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.3.3
  - pluggy=0.13.1
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyct=0.4.8
  - pydocstyle=5.1.1
  - pyembree=0.1.6
  - pyflakes=2.2.0
  - pygments=2.7.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.24.0
  - rope=0.18.0
  - rtree=0.9.7
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - scooby=0.5.6
  - seaborn=0.11.0
  - secretstorage=3.1.2
  - setuptools=52.0.0
  - shapely=1.7.1
  - sip=4.19.24
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.33.0
  - tbb=2020.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.56.0
  - traitlets=5.0.5
  - trimesh=3.9.1
  - ujson=4.0.1
  - urllib3=1.25.11
  - vtk=8.2.0
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - wurlitzer=2.0.1
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxt=1.1.5
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
      - absl-py==0.15.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - distro==1.5.0
      - flatbuffers==1.12
      - freetype-py==2.2.0
      - gast==0.3.3
      - google-auth==2.23.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - importlib-metadata==6.8.0
      - keras-preprocessing==1.1.2
      - markdown==3.5
      - markupsafe==2.1.3
      - mesh-to-sdf==0.0.12
      - numpy==1.19.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - overlap==0.0.5
      - platformdirs==3.11.0
      - pooch==1.8.0
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyglet==1.5.14
      - pyopengl==3.1.0
      - pyrender==0.1.43
      - pyvista==0.28.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-build==0.11.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.4.1
      - tensorflow-estimator==2.4.0
      - termcolor==1.1.0
      - transforms3d==0.3.1
      - typing-extensions==3.7.4.3
      - werkzeug==3.0.1
      - wrapt==1.12.1
